name: Azure Machine Learning training and deployment
on:
  push:
    branches:
      - "main"
jobs:
  score:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out repository
      id: checkout_repository
      uses: actions/checkout@v2
    
    - name: Setup Python
      id: setup_python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      id: install_dependencies
      run: |
        python -m pip install azureml-core azureml-pipeline numpy pandas
    
    - name: Deploy Scoring
      id: run_scoring
      env:
        SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
        RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
        WORKSPACE_NAME: ${{ secrets.WORKSPACE }}
      run: |
        python scoring/aci_deploy.py